spring.application.name=catalogo-produtos
spring.profiles.active=dev

server.port=8080
server.address=0.0.0.0

management.endpoints.web.exposure.include=health,info

server.error.include-stacktrace=never
server.error.include-message=always
